# Generated by Django 6.0.3 on 2026-03-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.CharField(max_length=30, unique=True)),
                ('encounter_date', models.DateField()),
                ('encounter_type', models.CharField(default='diabetic_eye_screening', max_length=50)),
                ('screening_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('images_uploaded', 'Images Uploaded'), ('under_review', 'Under Review'), ('report_ready', 'Report Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('visual_acuity_left', models.CharField(blank=True, max_length=20)),
                ('visual_acuity_right', models.CharField(blank=True, max_length=20)),
                ('diabetes_duration', models.CharField(blank=True, max_length=50)),
                ('symptoms_notes', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
            ],
            options={
                'ordering': ['-encounter_date', '-created_at'],
            },
        ),
    ]
