# Generated by Django 6.0.3 on 2026-05-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='dilation_drops_used',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='dilation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='iop_after_dilation_left',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='iop_after_dilation_right',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='iop_before_dilation_left',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='iop_before_dilation_right',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
