# Generated by Django 6.0.3 on 2026-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_screeningencounter_dilation_drops_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='left_corrected_pinhole_va',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='left_unaided_va',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='left_va_method',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('corrected', 'Corrected'), ('pinhole', 'Pinhole')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='right_corrected_pinhole_va',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='right_unaided_va',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='right_va_method',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('corrected', 'Corrected'), ('pinhole', 'Pinhole')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='screeningencounter',
            name='encounter_type',
            field=models.CharField(default='retinal_assessment', max_length=50),
        ),
    ]
