# Generated by Django 6.0.3 on 2026-07-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_screeningencounter_left_corrected_pinhole_va_and_more'),
        ('organizations', '0005_organizationprofile'),
        ('referrals', '0006_alter_hospitalreferral_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='hospital_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_encounters', to='referrals.hospitalreferral'),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='originating_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_screening_encounters', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='payment_responsibility',
            field=models.CharField(choices=[('patient', 'Patient'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('programme', 'Programme Sponsor'), ('waived', 'Waived')], default='hospital', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='programme',
            field=models.CharField(choices=[('diabetic_screening', 'Diabetic Retinal Assessment')], default='diabetic_screening', max_length=40),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='source_type',
            field=models.CharField(choices=[('hospital_referral', 'Hospital Referral'), ('clinic_direct', 'Clinic Direct')], default='hospital_referral', max_length=30),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='workflow_route',
            field=models.CharField(choices=[('sentinel_managed', 'Sentinel Managed'), ('clinic_managed', 'Clinic Managed')], default='sentinel_managed', max_length=30),
        ),
    ]
