# Generated by Django 6.0.3 on 2026-07-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_screeningencounter_hospital_referral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='source_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='source_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_source_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='source_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
