# Generated by Django 6.0.3 on 2026-08-14 05:08

import django.db.models.deletion
import encounters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0012_screeningencounter_service_branch'),
        ('organizations', '0008_alter_organization_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='service_delivery_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AssessmentServiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_reference', models.CharField(default=encounters.models.assessment_session_reference, editable=False, max_length=40, unique=True)),
                ('service_date', models.DateField()),
                ('location_type', models.CharField(choices=[('mobile', 'Mobile'), ('hospital', 'Hospital'), ('clinic', 'Clinic')], max_length=20)),
                ('provider_type', models.CharField(choices=[('sentinel', 'Sentinel'), ('service_partner', 'Service partner')], max_length=30)),
                ('sentinel_arranged_transport', models.BooleanField(default=False)),
                ('camera_team_rate', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('logistics_allocation_rate', models.DecimalField(decimal_places=2, default=2500, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_assessment_sessions', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_assessment_sessions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_assessment_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessment_sessions', to=settings.AUTH_USER_MODEL)),
                ('participating_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_service_sessions', to='organizations.organization')),
                ('service_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_service_sessions', to='organizations.organizationbranch')),
                ('service_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_assessment_service_sessions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='service_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='encounters.assessmentservicesession'),
        ),
        migrations.AddIndex(
            model_name='assessmentservicesession',
            index=models.Index(fields=['status', 'service_date'], name='encounters__status_66d051_idx'),
        ),
    ]
