# Generated by Django 6.0.3 on 2026-08-28 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocularinvestigation',
            name='asset_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocular_investigation_assets', to='organizations.organizationbranch'),
        ),
        migrations.AddField(
            model_name='ocularinvestigation',
            name='asset_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocular_investigation_assets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='ocularinvestigation',
            name='content_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ocularinvestigation',
            name='private_object_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ocularinvestigation',
            name='storage_kind',
            field=models.CharField(choices=[('default_media', 'Default media'), ('private_clinical', 'Private clinical')], default='default_media', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='ocularinvestigation',
            constraint=models.CheckConstraint(condition=models.Q(('storage_kind', 'default_media'), models.Q(('private_object_key__gt', ''), ('content_sha256__gt', ''), ('asset_organization__isnull', False), ('asset_branch__isnull', False)), _connector='OR'), name='private_investigation_requires_metadata'),
        ),
    ]
