# Generated by Django 6.0.3 on 2026-08-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classify_only_unambiguous_historical_packages(apps, schema_editor):
    Encounter = apps.get_model("encounters", "ScreeningEncounter")
    Encounter.objects.filter(
        service_package__isnull=True,
        programme="diabetic_screening",
    ).update(service_package="diabetic_retinal_assessment")
    Encounter.objects.filter(
        service_package__isnull=True,
        programme="combined_assessment",
    ).update(service_package="combined_diabetic_eye_health")


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0014_ocularinvestigation_asset_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningencounter',
            name='assessment_location_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='screeningencounter',
            name='service_package',
            field=models.CharField(blank=True, choices=[('diabetic_retinal_assessment', 'Diabetic Retinal Assessment'), ('eye_health_screening', 'Targeted Retinal and Glaucoma-Risk Screening'), ('combined_diabetic_eye_health', 'Combined Diabetic Retinal Assessment and Targeted Glaucoma-Risk Screening'), ('comprehensive_ocular_assessment', 'Comprehensive Ocular Assessment')], help_text='Authoritative clinical service package. Historical unclassified ocular episodes remain blank.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screeningencounter',
            name='programme',
            field=models.CharField(choices=[('diabetic_screening', 'Diabetic Retinal Assessment'), ('eye_health_screening', 'Targeted Retinal and Glaucoma-Risk Screening'), ('ocular_diagnostics', 'Comprehensive Ocular Assessment'), ('combined_assessment', 'Combined Diabetic Retinal Assessment and Targeted Glaucoma-Risk Screening')], default='diabetic_screening', max_length=40),
        ),
        migrations.RunPython(
            classify_only_unambiguous_historical_packages,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='EncounterServicePackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_package', models.CharField(blank=True, default='', max_length=50)),
                ('new_package', models.CharField(choices=[('diabetic_retinal_assessment', 'Diabetic Retinal Assessment'), ('eye_health_screening', 'Targeted Retinal and Glaucoma-Risk Screening'), ('combined_diabetic_eye_health', 'Combined Diabetic Retinal Assessment and Targeted Glaucoma-Risk Screening'), ('comprehensive_ocular_assessment', 'Comprehensive Ocular Assessment')], max_length=50)),
                ('reason', models.TextField()),
                ('diabetic_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_package_corrections', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_package_events', to='encounters.screeningencounter')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
