# Generated for Sentinel Finance Batch 1.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_organizationprofile"),
        ("encounters", "0005_screeningencounter_source_overridden_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("programme", models.CharField(default="diabetic_screening", max_length=80)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("suspended", "Suspended"), ("expired", "Expired")], default="draft", max_length=20)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("payment_terms_days", models.PositiveIntegerField(default=0)),
                ("credit_allowed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_contracts", to="organizations.organization")),
            ],
            options={"ordering": ["-effective_from", "organization__name"]},
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("service_type", models.CharField(default="retinal_assessment", max_length=80)),
                ("source_type", models.CharField(blank=True, default="", max_length=40)),
                ("workflow_route", models.CharField(blank=True, default="", max_length=40)),
                ("payment_responsibility", models.CharField(blank=True, default="", max_length=40)),
                ("equipment_owner_type", models.CharField(blank=True, default="", max_length=40)),
                ("min_monthly_volume", models.PositiveIntegerField(blank=True, null=True)),
                ("max_monthly_volume", models.PositiveIntegerField(blank=True, null=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pricing_rules", to="finance.partnercontract")),
            ],
            options={"ordering": ["priority", "-effective_from", "name"]},
        ),
        migrations.CreateModel(
            name="AllocationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("beneficiary_role", models.CharField(choices=[("sentinel", "Sentinel"), ("hospital", "Hospital"), ("clinic", "Clinic"), ("field_partner", "Field Partner"), ("logistics", "Logistics"), ("other", "Other")], max_length=30)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("calculation_type", models.CharField(choices=[("fixed", "Fixed amount"), ("percentage", "Percentage")], max_length=20)),
                ("fixed_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("percentage", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("beneficiary_organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="finance_allocation_rules", to="organizations.organization")),
                ("pricing_rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocation_rules", to="finance.pricingrule")),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.CreateModel(
            name="EncounterFinancialRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("unpriced", "Unpriced"), ("priced", "Priced"), ("awaiting_payment", "Awaiting payment"), ("wallet_reserved", "Wallet reserved"), ("approved_credit", "Approved credit"), ("financially_secured", "Financially secured"), ("captured", "Captured"), ("ready_for_release", "Ready for release"), ("settled", "Settled"), ("refunded", "Refunded"), ("cancelled", "Cancelled"), ("exception", "Exception")], default="unpriced", max_length=30)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("gross_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("allocated_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("outstanding_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("financially_releasable", models.BooleanField(default=False)),
                ("pricing_snapshot", models.JSONField(blank=True, default=dict)),
                ("exception_reason", models.TextField(blank=True, default="")),
                ("priced_at", models.DateTimeField(blank=True, null=True)),
                ("secured_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_records", to="finance.partnercontract")),
                ("encounter", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="financial_record", to="encounters.screeningencounter")),
                ("pricing_rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_records", to="finance.pricingrule")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="EncounterAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("beneficiary_role", models.CharField(choices=[("sentinel", "Sentinel"), ("hospital", "Hospital"), ("clinic", "Clinic"), ("field_partner", "Field Partner"), ("logistics", "Logistics"), ("other", "Other")], max_length=30)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("rule_snapshot", models.JSONField(blank=True, default=dict)),
                ("allocation_rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="generated_allocations", to="finance.allocationrule")),
                ("beneficiary_organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="encounter_allocations", to="organizations.organization")),
                ("financial_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="finance.encounterfinancialrecord")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=80)),
                ("previous_status", models.CharField(blank=True, default="", max_length=30)),
                ("new_status", models.CharField(blank=True, default="", max_length=30)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_audit_entries", to=settings.AUTH_USER_MODEL)),
                ("financial_record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_entries", to="finance.encounterfinancialrecord")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="partnercontract", index=models.Index(fields=["organization", "programme", "status"], name="finance_par_organiz_0f42bb_idx")),
        migrations.AddIndex(model_name="partnercontract", index=models.Index(fields=["effective_from", "effective_to"], name="finance_par_effecti_541fd8_idx")),
        migrations.AddIndex(model_name="pricingrule", index=models.Index(fields=["contract", "is_active", "service_type"], name="finance_pri_contrac_2cf91c_idx")),
        migrations.AddIndex(model_name="pricingrule", index=models.Index(fields=["source_type", "workflow_route"], name="finance_pri_source__7549e3_idx")),
        migrations.AddIndex(model_name="encounterfinancialrecord", index=models.Index(fields=["status", "financially_releasable"], name="finance_enc_status_093a6f_idx")),
        migrations.AddIndex(model_name="encounterfinancialrecord", index=models.Index(fields=["created_at"], name="finance_enc_created_677d8f_idx")),
    ]
