# Generated by Django 6.0.3 on 2026-07-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='encounterfinancialrecord',
            new_name='finance_enc_status_927306_idx',
            old_name='finance_enc_status_093a6f_idx',
        ),
        migrations.RenameIndex(
            model_name='encounterfinancialrecord',
            new_name='finance_enc_created_e87002_idx',
            old_name='finance_enc_created_677d8f_idx',
        ),
        migrations.RenameIndex(
            model_name='partnercontract',
            new_name='finance_par_organiz_19ba43_idx',
            old_name='finance_par_organiz_0f42bb_idx',
        ),
        migrations.RenameIndex(
            model_name='partnercontract',
            new_name='finance_par_effecti_9a5fb1_idx',
            old_name='finance_par_effecti_541fd8_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='finance_pri_contrac_14486b_idx',
            old_name='finance_pri_contrac_2cf91c_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='finance_pri_source__55c62e_idx',
            old_name='finance_pri_source__7549e3_idx',
        ),
    ]
