# Generated by Django 6.0.3 on 2026-08-14 19:56

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('finance', '0012_provision_finance_groups'),
        ('organizations', '0008_alter_organization_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartnerSettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('assessment_count', models.PositiveIntegerField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_evidence', models.FileField(blank=True, null=True, upload_to=finance.models.service_partner_payment_evidence_path)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_service_partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_service_partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_service_partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_service_partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_service_partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('service_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_settlement_batches', to='organizations.organization')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePartnerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earning_reference', models.CharField(default=finance.models.service_partner_earning_reference, editable=False, max_length=24, unique=True)),
                ('assessment_date', models.DateField()),
                ('session_reference', models.CharField(max_length=40)),
                ('provider_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('rate_snapshot', models.JSONField(default=dict)),
                ('trigger_source', models.CharField(max_length=40)),
                ('earned_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('settlement_pending', 'Settlement pending'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='available', max_length=24)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_earning', to='encounters.screeningencounter')),
                ('financial_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_earning', to='finance.encounterfinancialrecord')),
                ('service_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_earnings', to='organizations.organization')),
                ('service_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_earnings', to='encounters.assessmentservicesession')),
                ('active_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_earnings', to='finance.servicepartnersettlementbatch')),
            ],
            options={
                'ordering': ['-assessment_date', 'earning_reference'],
            },
        ),
        migrations.CreateModel(
            name='ServicePartnerSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.servicepartnersettlementbatch')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='finance.servicepartnerearning')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicepartnersettlementbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('external_reference',), name='fin_unique_partner_payment_ref'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnersettlementbatch',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0), ('final_amount__gt', 0)), name='fin_partner_settlement_positive'),
        ),
        migrations.AddIndex(
            model_name='servicepartnerearning',
            index=models.Index(fields=['service_partner', 'status', 'assessment_date'], name='fin_partner_earn_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnerearning',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_partner_earning_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnersettlementitem',
            constraint=models.UniqueConstraint(fields=('batch', 'earning'), name='fin_unique_partner_settlement_item'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnersettlementitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_partner_item_positive'),
        ),
    ]
