# Generated by Django 6.0.3 on 2026-08-14 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('finance', '0013_servicepartnersettlementbatch_servicepartnerearning_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartnerAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Carried forward'), ('settlement_pending', 'Settlement pending'), ('applied', 'Applied'), ('offset_without_payment', 'Offset without payment')], default='available', max_length=24)),
                ('posted_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePartnerCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='servicepartnersettlementitem',
            name='fin_partner_item_positive',
        ),
        migrations.AlterField(
            model_name='servicepartnersettlementitem',
            name='earning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='finance.servicepartnerearning'),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='active_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_adjustments', to='finance.servicepartnersettlementbatch'),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_adjustments', to='encounters.screeningencounter'),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='financial_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_adjustments', to='finance.encounterfinancialrecord'),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='original_earning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.servicepartnerearning'),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='service_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_partner_adjustments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='servicepartnersettlementitem',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='finance.servicepartneradjustment'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnersettlementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment__isnull', True), ('earning__isnull', False)), models.Q(('adjustment__isnull', False), ('earning__isnull', True)), _connector='OR'), name='fin_partner_item_one_source'),
        ),
        migrations.AddField(
            model_name='servicepartnercorrectionrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_service_partner_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartnercorrectionrequest',
            name='earning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='finance.servicepartnerearning'),
        ),
        migrations.AddField(
            model_name='servicepartnercorrectionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_service_partner_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepartneradjustment',
            name='correction_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='finance.servicepartnercorrectionrequest'),
        ),
        migrations.AddConstraint(
            model_name='servicepartnercorrectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_partner_correction_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicepartneradjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lt', 0)), name='fin_partner_adjustment_negative'),
        ),
    ]
