# Generated by Django 6.0.3 on 2026-08-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_servicepartneradjustment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicepartnersettlementitem',
            constraint=models.UniqueConstraint(fields=('batch', 'adjustment'), name='fin_unique_partner_adjustment_item'),
        ),
    ]
