# Generated by Django 6.0.3 on 2026-08-29 20:48

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0014_ocularinvestigation_asset_branch_and_more'),
        ('finance', '0015_servicepartnersettlementitem_fin_unique_partner_adjustment_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsorship_reference', models.CharField(default=finance.models.sponsorship_reference, editable=False, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('complimentary_client_service', 'Complimentary client service'), ('approved_promotional_screening', 'Approved promotional screening'), ('hardship_support', 'Hardship support'), ('approved_programme_sponsorship', 'Approved programme sponsorship'), ('correction_replacement', 'Correction or replacement')], max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved and reserved'), ('captured', 'Captured'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('patient_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_service_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pricing_snapshot', models.JSONField(default=dict)),
                ('allocation_snapshot', models.JSONField(default=list)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_encounter_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encounter_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_encounter_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_sponsorship', to='encounters.screeningencounter')),
                ('financial_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship', to='finance.encounterfinancialrecord')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship', to='finance.walletreservation')),
                ('sponsor_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to='finance.organizationwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('source_status', models.CharField(blank=True, default='', max_length=20)),
                ('target_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_events', to=settings.AUTH_USER_MODEL)),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.encountersponsorship')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_reference', models.CharField(default=finance.models.treasury_transfer_reference, editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('purpose', models.TextField()),
                ('destination_label', models.CharField(max_length=180)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('evidence', models.FileField(blank=True, null=True, upload_to=finance.models.finance_action_evidence_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('executed', 'Execution recorded'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('available_surplus_snapshot', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_treasury_transfers', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_treasury_transfers', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_treasury_transfers', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transfer', to='finance.walletledgerentry')),
                ('reversal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_treasury_transfer', to='finance.walletledgerentry')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transfers', to='finance.organizationwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('source_status', models.CharField(blank=True, default='', max_length=20)),
                ('target_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transfer_events', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.treasurytransfer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='encountersponsorship',
            index=models.Index(fields=['status', 'created_at'], name='fin_sponsor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='encountersponsorship',
            index=models.Index(fields=['sponsor_wallet', 'status'], name='fin_sponsor_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransfer',
            index=models.Index(fields=['status', 'created_at'], name='fin_transfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurytransfer',
            index=models.Index(fields=['wallet', 'status'], name='fin_transfer_wallet_idx'),
        ),
        migrations.AddConstraint(
            model_name='encountersponsorship',
            constraint=models.CheckConstraint(condition=models.Q(('patient_amount', 0)), name='fin_sponsor_patient_zero'),
        ),
        migrations.AddConstraint(
            model_name='encountersponsorship',
            constraint=models.CheckConstraint(condition=models.Q(('gross_service_value__gt', 0)), name='fin_sponsor_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_transfer_amount_positive'),
        ),
    ]
