# Generated by Django 6.0.3 on 2026-09-07 20:33

import django.core.serializers.json
import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_service_components_historical_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterfinancialrecord',
            name='disposition',
            field=models.CharField(choices=[('standard', 'Standard'), ('complimentary_non_cash', 'Complimentary (non-cash)')], default='standard', max_length=30),
        ),
        migrations.AddField(
            model_name='treasurytransfer',
            name='reversal_evidence',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.finance_action_evidence_path),
        ),
        migrations.AddField(
            model_name='treasurytransfer',
            name='reversal_kind',
            field=models.CharField(blank=True, choices=[('returned_funds', 'Returned funds'), ('bookkeeping_correction', 'Incorrect debit correction')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='treasurytransfer',
            name='reversal_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='ComplimentaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('reason', models.TextField()),
                ('gross_service_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('pricing_snapshot', models.JSONField(default=dict)),
                ('allocation_snapshot', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complimentary_requests', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complimentary_decisions', to=settings.AUTH_USER_MODEL)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complimentary_requests', to='finance.encounterfinancialrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComplimentaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('source_status', models.CharField(blank=True, max_length=20)),
                ('target_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.complimentaryrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='complimentaryrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'approved'])), fields=('financial_record',), name='fin_one_active_complimentary'),
        ),
        migrations.AddConstraint(
            model_name='complimentaryrequest',
            constraint=models.CheckConstraint(condition=models.Q(('gross_service_value__gt', 0)), name='fin_complimentary_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='complimentaryrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected']), _negated=True), models.Q(('decided_by__isnull', False), models.Q(('decided_by', models.F('created_by')), _negated=True)), _connector='OR'), name='fin_complimentary_checker'),
        ),
        migrations.AddConstraint(
            model_name='complimentaryevent',
            constraint=models.UniqueConstraint(fields=('request', 'action'), name='fin_complimentary_event_once'),
        ),
        migrations.AddConstraint(
            model_name='encounterfinancialrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposition', 'complimentary_non_cash'), _negated=True), models.Q(('allocated_amount', 0), ('captured_at__isnull', True), ('collecting_organization__isnull', True), ('collector_type', 'none'), ('financially_releasable', True), ('gross_amount__gt', 0), ('outstanding_amount', 0), ('payer_organization__isnull', True), ('payer_type', 'waived'), ('payment_method', 'waived'), ('status', 'ready_for_release')), _connector='OR'), name='fin_complimentary_non_cash'),
        ),
        migrations.AddConstraint(
            model_name='treasurytransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('reversal_reference', ''), _negated=True), fields=('reversal_reference',), name='fin_unique_reversal_reference'),
        ),
    ]
