# Generated by Django 6.0.3 on 2026-09-08 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_complimentary_and_reversal_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeactionrequest',
            name='approved_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='financeactionrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeactionrequest',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_finance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeactionrequest',
            name='reversal_kind',
            field=models.CharField(blank=True, choices=[('returned_funds', 'Returned funds'), ('bookkeeping_correction', 'Incorrect debit correction')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='financeactionrequest',
            name='treasury_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_requests', to='finance.treasurytransfer'),
        ),
        migrations.AlterField(
            model_name='financeactionrequest',
            name='action_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('treasury_reversal', 'Treasury reversal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financeactionrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Approved, awaiting execution'), ('executed', 'Executed'), ('pending', 'Pending approval'), ('approved', 'Approved and posted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='financeactionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'treasury_reversal'), ('status__in', ['draft', 'pending', 'authorized', 'executed'])), fields=('treasury_transfer',), name='fin_one_active_transfer_reversal'),
        ),
        migrations.AddConstraint(
            model_name='financeactionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'treasury_reversal'), ('status__in', ['draft', 'pending', 'authorized', 'executed'])), fields=('external_reference',), name='fin_unique_active_reversal_ref'),
        ),
        migrations.AddConstraint(
            model_name='financeactionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'treasury_reversal'), _negated=True), models.Q(('amount__gt', 0), ('treasury_transfer__isnull', False)), _connector='OR'), name='fin_reversal_transfer_required'),
        ),
        migrations.AddConstraint(
            model_name='settlementitem',
            constraint=models.UniqueConstraint(fields=('batch', 'allocation'), name='fin_unique_batch_allocation'),
        ),
    ]
