# Generated by Django 6.0.3 on 2026-04-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_organization_type'),
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        ('reports', '0002_structuredreport_ops_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=50, unique=True)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('referral_status', models.CharField(choices=[('submitted', 'Submitted'), ('matched', 'Matched'), ('booked', 'Booked'), ('no_show', 'No Show'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_status', models.CharField(blank=True, max_length=50)),
                ('no_show', models.BooleanField(default=False)),
                ('report_ready', models.BooleanField(default=False)),
                ('hospital_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_status', models.CharField(choices=[('not_due', 'Not Due'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='not_due', max_length=30)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(default='sentinel_ops', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_hospital_referrals', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_referrals', to='patients.patient')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_referrals', to='reports.structuredreport')),
                ('source_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_hospital_referrals', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
