# Generated by Django 6.0.3 on 2026-04-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_organization_type'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalIntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=60, unique=True)),
                ('patient_id_text', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('patient_sex', models.CharField(max_length=30)),
                ('hospital_mrn', models.CharField(blank=True, max_length=100)),
                ('diabetes_type', models.CharField(max_length=50)),
                ('reason_for_referral', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('baserow_row_id', models.IntegerField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('linked_to_referral', 'Linked To Referral'), ('failed', 'Failed')], default='submitted', max_length=30)),
                ('linked_referral_id', models.CharField(blank=True, max_length=50)),
                ('linked_patient_id', models.CharField(blank=True, max_length=50)),
                ('processing_note', models.TextField(blank=True)),
                ('submitted_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_intake_submissions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
