# Generated by Django 6.0.3 on 2026-04-20 19:07

import django.db.models.deletion
from django.db import migrations, models

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        ('referrals', '0002_hospitalintakesubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalreferral',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='hospitalreferral',
            name='appointment_status',
        ),
        migrations.RemoveField(
            model_name='hospitalreferral',
            name='no_show',
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='baserow_row_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='diabetes_type',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='hospital_mrn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='last_name',
            field=models.CharField(default='Legacy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='patient_id_text',
            field=models.CharField(default='legacy-patient', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='patient_sex',
            field=models.CharField(default='prefer not to say', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='reason_for_referral',
            field=models.TextField(default='legacy migration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalreferral',
            name='submitted_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_referrals', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='referral_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='referral_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clinic_matched', 'Clinic Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='source_system',
            field=models.CharField(default='hospital_portal', max_length=50),
        ),
        migrations.DeleteModel(
            name='HospitalIntakeSubmission',
        ),
    ]
