# Generated by Django 6.0.3 on 2026-05-02 02:17

import referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_remove_hospitalreferral_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreferral',
            name='diabetes_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='patient_id_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='referral_id',
            field=models.CharField(default=referrals.models.generate_referral_id, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='referral_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clinic_matched', 'Clinic Matched'), ('in_clinic', 'In Clinic'), ('report_issued', 'Report Issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30),
        ),
    ]
