# Generated by Django 6.0.3 on 2026-05-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_organization_type'),
        ('referrals', '0004_alter_hospitalreferral_diabetes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreferral',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='patient_sex',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitalreferral',
            name='source_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_hospital_referrals', to='organizations.organization'),
        ),
    ]
