# Generated by Django 6.0.3 on 2026-07-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_alter_hospitalreferral_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreferral',
            name='referral_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clinic_matched', 'Clinic Matched'), ('in_clinic', 'In Clinic'), ('report_created', 'Report Created'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('report_issued', 'Report Issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=30),
        ),
    ]
