# Generated by Django 6.0.3 on 2026-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_address_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('sentinel', 'Sentinel')], default='clinic', max_length=20),
        ),
    ]
