# Generated by Django 6.0.3 on 2026-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='hospital_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='screening_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
    ]
