# Generated by Django 6.0.3 on 2026-07-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_mode', models.CharField(choices=[('sentinel_managed', 'Sentinel Managed'), ('clinic_managed', 'Clinic Managed'), ('hybrid', 'Hybrid')], default='sentinel_managed', max_length=30)),
                ('referral_requirement', models.CharField(choices=[('required', 'Referral Required'), ('optional', 'Referral Optional'), ('not_required', 'Referral Not Required')], default='required', max_length=30)),
                ('patient_ownership', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('shared', 'Shared')], default='shared', max_length=20)),
                ('can_create_direct_patients', models.BooleanField(default=False)),
                ('can_issue_reports_directly', models.BooleanField(default=False)),
                ('electronic_signature_required', models.BooleanField(default=False)),
                ('sentinel_review_policy', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('unavailable', 'Unavailable')], default='mandatory', max_length=20)),
                ('default_payment_responsibility', models.CharField(choices=[('patient', 'Patient'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('programme', 'Programme Sponsor'), ('waived', 'Waived')], default='hospital', max_length=20)),
                ('branding_policy', models.CharField(choices=[('sentinel_only', 'Sentinel Only'), ('organization_only', 'Organization Only'), ('organization_and_sentinel', 'Organization + Sentinel'), ('hospital_and_sentinel', 'Hospital + Sentinel'), ('hospital_clinic_sentinel', 'Hospital + Clinic + Sentinel')], default='organization_and_sentinel', max_length=40)),
                ('default_programme', models.CharField(choices=[('diabetic_screening', 'Diabetic Screening'), ('ocular_diagnostics', 'Ocular Diagnostics')], default='diabetic_screening', max_length=40)),
                ('subscription_tier', models.CharField(choices=[('pilot', 'Pilot'), ('clinic_core', 'Clinic Core'), ('managed_review', 'Managed Review'), ('hybrid', 'Hybrid'), ('enterprise', 'Enterprise')], default='pilot', max_length=30)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('clinic_direct_screening_enabled', models.BooleanField(default=False)),
                ('ocular_diagnostics_enabled', models.BooleanField(default=False)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('settings_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability_profile', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
    ]
