# Generated by Django 6.0.3 on 2026-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_partnernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('sentinel', 'Sentinel'), ('service_partner', 'Service Partner')], default='clinic', max_length=20),
        ),
    ]
