# Generated by Django 6.0.3 on 2026-03-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=30, unique=True)),
                ('review_date', models.DateField()),
                ('dr_grade', models.CharField(blank=True, max_length=50)),
                ('maculopathy_grade', models.CharField(blank=True, max_length=50)),
                ('ungradable', models.BooleanField(default=False)),
                ('urgency_outcome', models.CharField(choices=[('routine_followup', 'Routine Follow-up'), ('early_review', 'Early Review'), ('urgent_referral', 'Urgent Referral'), ('ophthalmology_required', 'Ophthalmology Required'), ('image_retake', 'Image Retake')], default='routine_followup', max_length=50)),
                ('recommendation', models.TextField(blank=True)),
                ('next_followup_interval', models.CharField(blank=True, max_length=50)),
                ('report_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('issued', 'Issued')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='encounters.screeningencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
