# Generated by Django 6.0.3 on 2026-04-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='ops_review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='ops_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='ops_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed_by_ops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='payout_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='submitted_to_ops_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='submitted_to_ops_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted_to_ops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structuredreport',
            name='report_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('submitted_to_ops', 'Submitted to Ops'), ('ops_approved', 'Ops Approved'), ('ops_rejected', 'Ops Rejected'), ('issued', 'Issued')], default='draft', max_length=30),
        ),
    ]
