# Generated by Django 6.0.3 on 2026-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_structuredreport_ops_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='left_corrected_va',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/7.5', '6/7.5'), ('6/9', '6/9'), ('6/12', '6/12'), ('6/15', '6/15'), ('6/18', '6/18'), ('6/24', '6/24'), ('6/36', '6/36'), ('6/60', '6/60'), ('CF', 'Counting Fingers'), ('HM', 'Hand Movements'), ('PL', 'Perception of Light'), ('NPL', 'No Perception of Light')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='left_dr_grade',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('R0', 'R0 - No DR'), ('R1', 'R1 - Background DR'), ('R2', 'R2 - Pre-proliferative DR'), ('R3A', 'R3A - Active proliferative DR'), ('R3S', 'R3S - Stable treated proliferative DR'), ('U', 'Ungradable')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='left_maculopathy_grade',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('M0', 'M0 - No maculopathy'), ('M1', 'M1 - Maculopathy'), ('U', 'Ungradable')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='left_unaided_va',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/7.5', '6/7.5'), ('6/9', '6/9'), ('6/12', '6/12'), ('6/15', '6/15'), ('6/18', '6/18'), ('6/24', '6/24'), ('6/36', '6/36'), ('6/60', '6/60'), ('CF', 'Counting Fingers'), ('HM', 'Hand Movements'), ('PL', 'Perception of Light'), ('NPL', 'No Perception of Light')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='right_corrected_va',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/7.5', '6/7.5'), ('6/9', '6/9'), ('6/12', '6/12'), ('6/15', '6/15'), ('6/18', '6/18'), ('6/24', '6/24'), ('6/36', '6/36'), ('6/60', '6/60'), ('CF', 'Counting Fingers'), ('HM', 'Hand Movements'), ('PL', 'Perception of Light'), ('NPL', 'No Perception of Light')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='right_dr_grade',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('R0', 'R0 - No DR'), ('R1', 'R1 - Background DR'), ('R2', 'R2 - Pre-proliferative DR'), ('R3A', 'R3A - Active proliferative DR'), ('R3S', 'R3S - Stable treated proliferative DR'), ('U', 'Ungradable')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='right_maculopathy_grade',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('M0', 'M0 - No maculopathy'), ('M1', 'M1 - Maculopathy'), ('U', 'Ungradable')], max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='right_unaided_va',
            field=models.CharField(blank=True, choices=[('', 'Not Recorded'), ('6/4', '6/4'), ('6/5', '6/5'), ('6/6', '6/6'), ('6/7.5', '6/7.5'), ('6/9', '6/9'), ('6/12', '6/12'), ('6/15', '6/15'), ('6/18', '6/18'), ('6/24', '6/24'), ('6/36', '6/36'), ('6/60', '6/60'), ('CF', 'Counting Fingers'), ('HM', 'Hand Movements'), ('PL', 'Perception of Light'), ('NPL', 'No Perception of Light')], max_length=20),
        ),
    ]
