# Generated by Django 6.0.3 on 2026-07-11 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_structuredreport_left_corrected_va_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='hospital_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='hospital_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='structuredreport',
            name='report_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('ops_approved', 'Ops Approved'), ('ops_rejected', 'Ops Rejected'), ('issued', 'Issued')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='ReportStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('resubmitted', 'Resubmitted'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('hospital_viewed', 'Hospital Viewed'), ('hospital_downloaded', 'Hospital Downloaded')], max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_status_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='reports.structuredreport')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
