# Generated by Django 6.0.3 on 2026-07-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_screeningencounter_left_corrected_pinhole_va_and_more'),
        ('reports', '0004_structuredreport_hospital_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredreport',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_report', to='encounters.screeningencounter'),
        ),
    ]
