# Generated by Django 6.0.3 on 2026-07-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_structuredreport_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='report_owner',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('sentinel', 'Sentinel')], default='sentinel', max_length=20),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='sentinel_archive_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='signer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='signer_registration_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='signer_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='structuredreport',
            name='report_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('ops_approved', 'Ops Approved'), ('ops_rejected', 'Ops Rejected'), ('issued', 'Issued'), ('clinic_signed', 'Clinic Signed'), ('clinic_issued', 'Clinic Issued')], default='draft', max_length=30),
        ),
    ]
