# Generated by Django 6.0.3 on 2026-07-16 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_structuredreport_issued_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='distribution_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('awaiting_distribution', 'Awaiting Distribution'), ('released_to_hospital', 'Released to Hospital'), ('completed', 'Completed')], default='not_ready', max_length=40),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='hospital_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='hospital_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_released_to_hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='patient_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='patient_delivery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportstatusevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('resubmitted', 'Resubmitted'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('hospital_viewed', 'Hospital Viewed'), ('hospital_downloaded', 'Hospital Downloaded'), ('queued_for_distribution', 'Queued for Distribution'), ('released_to_hospital', 'Released to Hospital')], max_length=40),
        ),
    ]
