# Generated by Django 6.0.3 on 2026-07-16 20:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_masterpatient_historicalrecordaccessrequest_and_more'),
        ('reports', '0007_structuredreport_distribution_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredreport',
            name='clinical_summary_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='final_clinical_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='generated_clinical_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='structuredreport',
            name='recall_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('scheduled', 'Scheduled'), ('due_soon', 'Due Soon'), ('due', 'Due'), ('overdue', 'Overdue'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='not_set', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportstatusevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('resubmitted', 'Resubmitted'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('clinic_signed', 'Clinic Signed'), ('clinic_issued', 'Clinic Issued'), ('queued_for_distribution', 'Queued for Distribution'), ('released_to_hospital', 'Released to Hospital'), ('hospital_viewed', 'Hospital Viewed'), ('hospital_downloaded', 'Hospital Downloaded')], max_length=40),
        ),
        migrations.CreateModel(
            name='PatientReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('include_images', models.BooleanField(default=False)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_deliveries', to='patients.patient')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_deliveries', to='reports.structuredreport')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_report_deliveries_requested', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_report_deliveries_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
