# Generated by Django 6.0.3 on 2026-08-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0015_screeningencounter_assessment_location_snapshot_and_more'),
        ('reports', '0010_report_clinical_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeHealthScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('no_immediate_concern', 'No immediate concern identified within the areas assessed'), ('routine_eye_examination', 'Routine comprehensive eye examination advised'), ('further_assessment', 'Further assessment recommended'), ('urgent_ophthalmology', 'Urgent ophthalmology assessment recommended'), ('inconclusive_repeat', 'Inconclusive — repeat testing required')], default='', max_length=40)),
                ('selected_advice', models.JSONField(blank=True, default=list)),
                ('advice', models.TextField(blank=True, default='')),
                ('structured_findings', models.JSONField(blank=True, default=dict)),
                ('generated_suggestion', models.TextField(blank=True, default='')),
                ('clinical_summary', models.TextField(blank=True, default='')),
                ('right_visual_field_result', models.TextField(blank=True, default='')),
                ('left_visual_field_result', models.TextField(blank=True, default='')),
                ('right_fundus_result', models.TextField(blank=True, default='')),
                ('left_fundus_result', models.TextField(blank=True, default='')),
                ('selected_fundus_upload_ids', models.JSONField(blank=True, default=list)),
                ('selected_visual_field_investigation_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('preview_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('hospital_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eye_health_report', to='encounters.screeningencounter')),
                ('hospital_released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eye_health_reports_released_to_hospital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeHealthScreeningReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('clinical_snapshot', models.JSONField(default=dict)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('clinician_snapshot', models.JSONField(default=dict)),
                ('attachment_manifest', models.JSONField(blank=True, default=list)),
                ('pdf_object_key', models.CharField(blank=True, default='', max_length=500)),
                ('pdf_checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eye_health_report_versions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reports.eyehealthscreeningreport')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreport',
            name='finalized_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_for_report', to='reports.eyehealthscreeningreportversion'),
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreport',
            name='hospital_released_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_releases', to='reports.eyehealthscreeningreportversion'),
        ),
        migrations.AddConstraint(
            model_name='eyehealthscreeningreportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version_number'), name='eye_health_unique_version'),
        ),
    ]
