# Generated by Django 6.0.3 on 2026-08-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_eyehealthscreeningreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyehealthscreeningreport',
            name='correction_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreport',
            name='correction_source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_drafts', to='reports.eyehealthscreeningreportversion'),
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreportversion',
            name='correction_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreportversion',
            name='purpose',
            field=models.CharField(choices=[('initial', 'Initial'), ('correction', 'Correction')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='eyehealthscreeningreportversion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_versions', to='reports.eyehealthscreeningreportversion'),
        ),
    ]
