# Generated by Django 6.0.3 on 2026-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_eye_health_ops_review_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyehealthscreeningreport',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft / not submitted'), ('not_required', 'Ops review not required'), ('awaiting_ops', 'Awaiting Ops review'), ('approved', 'Ops approved'), ('returned_to_clinic', 'Returned to clinic'), ('legacy', 'Legacy finalized report')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='structuredreport',
            name='report_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('signed_off', 'Signed Off'), ('clinician_signed', 'Clinician Signed'), ('submitted_to_ops', 'Submitted to Ops'), ('returned_to_clinic', 'Returned to Clinic'), ('ops_approved', 'Ops Approved'), ('ops_rejected', 'Ops Rejected'), ('issued', 'Issued'), ('clinic_signed', 'Clinic Signed'), ('clinic_issued', 'Clinic Issued')], default='draft', max_length=30),
        ),
    ]
