# Generated by Django 6.0.3 on 2026-03-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=30, unique=True)),
                ('consent_type', models.CharField(choices=[('care_delivery', 'Care Delivery'), ('data_sharing', 'Data Sharing'), ('ai_training', 'AI Training'), ('research_use', 'Research Use')], max_length=30)),
                ('consent_status', models.CharField(choices=[('granted', 'Granted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=20)),
                ('consent_date', models.DateField()),
                ('captured_by', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='encounters.screeningencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
            ],
            options={
                'ordering': ['-consent_date', '-created_at'],
            },
        ),
    ]
