# Generated by Django 6.0.3 on 2026-07-12 00:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_currency_and_more'),
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('registration', 'Registration'), ('consent', 'Consent'), ('encounter', 'Encounter'), ('imaging', 'Imaging'), ('ai', 'AI'), ('report', 'Report'), ('referral', 'Referral'), ('payment', 'Payment'), ('hospital', 'Hospital'), ('system', 'System')], max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('encounter_id', models.CharField(blank=True, default='', max_length=120)),
                ('report_id', models.CharField(blank=True, default='', max_length=120)),
                ('referral_id', models.CharField(blank=True, default='', max_length=120)),
                ('payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('visibility', models.CharField(choices=[('all', 'All authorised portals'), ('clinic_ops', 'Clinic and Ops'), ('hospital_ops', 'Hospital and Ops'), ('ops_only', 'Ops only')], default='all', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_timeline_events', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['patient', '-occurred_at'], name='audit_patie_patient_301194_idx'), models.Index(fields=['category', '-occurred_at'], name='audit_patie_categor_2e412d_idx')],
            },
        ),
    ]
