# Generated by Django 6.0.3 on 2026-05-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0004_alter_hospitalreferral_diabetes_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('payment_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('exception', 'Exception')], default='draft', max_length=20)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_payments', to='referrals.hospitalreferral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
