# Generated by Django 6.0.3 on 2026-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_opsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsauditlog',
            name='action',
            field=models.CharField(choices=[('hospital_created', 'Hospital Created'), ('clinic_created', 'Clinic Created'), ('ops_user_created', 'Ops User Created'), ('payment_created', 'Payment Created'), ('payment_link_generated', 'Payment Link Generated'), ('payment_verified', 'Payment Verified'), ('clinic_assigned', 'Clinic Assigned'), ('report_approved', 'Report Approved'), ('report_returned', 'Report Returned to Clinic'), ('report_issued', 'Report Issued'), ('report_rejected', 'Report Rejected')], max_length=80),
        ),
    ]
