# Generated by Django 6.0.3 on 2026-07-16 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
        ('organizations', '0005_organizationprofile'),
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentinel_patient_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(blank=True, default='', max_length=20)),
                ('primary_phone', models.CharField(blank=True, default='', max_length=30)),
                ('primary_email', models.EmailField(blank=True, default='', max_length=254)),
                ('identity_status', models.CharField(choices=[('active', 'Active'), ('possible_duplicate', 'Possible Duplicate'), ('merged', 'Merged'), ('restricted', 'Restricted')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='patients.masterpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecordAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('consent_reference', models.CharField(max_length=120)),
                ('include_reports', models.BooleanField(default=True)),
                ('include_images', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_access_requests', to='consents.consentrecord')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_record_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_record_requests', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_record_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('master_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_access_requests', to='patients.masterpatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='master_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_records', to='patients.masterpatient'),
        ),
        migrations.CreateModel(
            name='PatientIdentityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('linked', 'Linked'), ('kept_separate', 'Kept Separate'), ('dismissed', 'Dismissed')], default='open', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reviews', to='patients.patient')),
                ('possible_master_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reviews', to='patients.masterpatient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_identity_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientOrganizationIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('hospital_mrn', 'Hospital MRN'), ('clinic_local_id', 'Clinic Local ID'), ('legacy_patient_id', 'Legacy Patient ID'), ('other', 'Other')], default='other', max_length=30)),
                ('local_identifier', models.CharField(max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('master_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_identities', to='patients.masterpatient')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_identities', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'identity_type'],
            },
        ),
        migrations.AddIndex(
            model_name='masterpatient',
            index=models.Index(fields=['last_name', 'first_name', 'date_of_birth'], name='patients_ma_last_na_4dcc36_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpatient',
            index=models.Index(fields=['primary_phone'], name='patients_ma_primary_95d6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpatient',
            index=models.Index(fields=['primary_email'], name='patients_ma_primary_31e24b_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalrecordaccessrequest',
            index=models.Index(fields=['requesting_organization', 'status', '-created_at'], name='patients_hi_request_e83670_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientidentityreview',
            constraint=models.UniqueConstraint(fields=('candidate_patient', 'possible_master_patient'), name='unique_patient_identity_review_pair'),
        ),
        migrations.AddConstraint(
            model_name='patientorganizationidentity',
            constraint=models.UniqueConstraint(fields=('organization', 'identity_type', 'local_identifier'), name='unique_org_patient_identifier'),
        ),
    ]
