# Generated by Django 6.0.3 on 2026-03-27 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload_id', models.CharField(max_length=30, unique=True)),
                ('eye_laterality', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('image_type', models.CharField(choices=[('fundus', 'Fundus'), ('oct', 'OCT'), ('other', 'Other')], default='fundus', max_length=20)),
                ('image_file', models.ImageField(upload_to='encounter_uploads/')),
                ('image_quality', models.CharField(choices=[('good', 'Good'), ('acceptable', 'Acceptable'), ('poor', 'Poor'), ('ungradable', 'Ungradable')], default='good', max_length=20)),
                ('gradable', models.BooleanField(default=True)),
                ('retake_required', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to='encounters.screeningencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
