# Generated by Django 6.0.3 on 2026-04-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('sentinel', 'Sentinel AI')], max_length=20)),
                ('ai_status', models.CharField(default='pending', max_length=20)),
                ('fundus_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('uncertain', 'Uncertain'), ('error', 'Error')], max_length=20, null=True)),
                ('prediction', models.CharField(blank=True, max_length=150, null=True)),
                ('referable', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('severity_label', models.CharField(blank=True, max_length=80, null=True)),
                ('image_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_flag', models.CharField(blank=True, max_length=80, null=True)),
                ('suggested_review_priority', models.CharField(blank=True, max_length=80, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('draft_note', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('heatmap_url', models.URLField(blank=True, null=True)),
                ('processed_image_url', models.URLField(blank=True, null=True)),
                ('raw_response_json', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='encounters.screeningencounter')),
                ('image_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='uploads.imageupload')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
