# Generated by Django 6.0.3 on 2026-04-24 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0002_patient_appointment_date_patient_assigned_clinic_and_more'),
        ('uploads', '0002_aianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('sentinel', 'Sentinel AI'), ('hybrid', 'Hybrid AI')], max_length=20),
        ),
        migrations.CreateModel(
            name='DatasetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('image_quality_label', models.CharField(default='good', max_length=50)),
                ('dr_grade', models.CharField(choices=[('no_dr', 'No DR'), ('mild_npdr', 'Mild NPDR'), ('moderate_npdr', 'Moderate NPDR'), ('severe_npdr', 'Severe NPDR'), ('pdr', 'Proliferative DR'), ('ungradable', 'Ungradable'), ('other', 'Other')], max_length=50)),
                ('maculopathy_grade', models.CharField(choices=[('m0', 'M0 - No maculopathy'), ('m1', 'M1 - Maculopathy present / suspected'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('referable', models.BooleanField(default=False)),
                ('referral_urgency', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent'), ('not_required', 'Not Required')], default='routine', max_length=30)),
                ('clinician_notes', models.TextField(blank=True, default='')),
                ('other_findings', models.TextField(blank=True, default='')),
                ('ai_prediction_at_label_time', models.CharField(blank=True, default='', max_length=150)),
                ('ai_provider_at_label_time', models.CharField(blank=True, default='', max_length=50)),
                ('ai_confidence_at_label_time', models.FloatField(blank=True, null=True)),
                ('ai_raw_response_at_label_time', models.JSONField(blank=True, null=True)),
                ('labelled_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_labels', to='encounters.screeningencounter')),
                ('image_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_label', to='uploads.imageupload')),
                ('labelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_labels_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_labels', to='patients.patient')),
            ],
            options={
                'ordering': ['-labelled_at'],
            },
        ),
    ]
