# Generated by Django 6.0.3 on 2026-04-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_structuredreport_ops_review_note_and_more'),
        ('uploads', '0003_alter_aianalysis_provider_datasetlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetlabel',
            name='ai_clinician_agreement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='ai_referable_at_label_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='disagreement_flag',
            field=models.CharField(choices=[('none', 'None'), ('ai_unavailable', 'AI Unavailable'), ('referable_mismatch', 'Referable Mismatch')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='label_source',
            field=models.CharField(choices=[('report_auto', 'Report Auto'), ('manual_admin', 'Manual Admin')], default='report_auto', max_length=30),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='quality_flag',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='report_status_at_label_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='source_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_labels', to='reports.structuredreport'),
        ),
        migrations.AlterField(
            model_name='datasetlabel',
            name='dr_grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetlabel',
            name='maculopathy_grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetlabel',
            name='referral_urgency',
            field=models.CharField(default='routine', max_length=50),
        ),
    ]
