# Generated by Django 6.0.3 on 2026-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_datasetlabel_ai_clinician_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlabel',
            name='disagreement_flag',
            field=models.CharField(choices=[('none', 'None'), ('ai_unavailable', 'AI Unavailable'), ('referable_mismatch', 'Referable Mismatch'), ('ai_missed_referable', 'AI Missed Referable'), ('ai_overcalled_referable', 'AI Overcalled Referable')], default='none', max_length=50),
        ),
    ]
