# Generated by Django 6.0.3 on 2026-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_datasetlabel_disagreement_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetlabel',
            name='corrected_visual_acuity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='diabetic_referable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='eye_laterality',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='unaided_visual_acuity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='vision_referral_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetlabel',
            name='vision_referral_reason',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
