# Generated by Django 6.0.3 on 2026-08-15 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        ('uploads', '0007_mobile_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImageImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archive_checksum_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('preview', 'Ready for review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='processing', max_length=20)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_pending', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_image_imports', to='organizations.organizationbranch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bulk_image_imports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bulk_image_imports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_image_imports', to='organizations.organization')),
                ('service_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_image_imports', to='encounters.assessmentservicesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkImageImportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_index', models.PositiveIntegerField()),
                ('mrn', models.CharField(blank=True, default='', max_length=120)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('proposed', 'Encounter proposed'), ('resolved', 'Resolved'), ('invalid', 'Invalid')], default='unresolved', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('safe_issue_code', models.CharField(blank=True, default='', max_length=80)),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='uploads.bulkimageimport')),
                ('proposed_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_bulk_image_groups', to='encounters.screeningencounter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_bulk_image_groups', to=settings.AUTH_USER_MODEL)),
                ('resolved_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_bulk_image_groups', to='encounters.screeningencounter')),
            ],
            options={
                'ordering': ['source_index'],
            },
        ),
        migrations.CreateModel(
            name='BulkImageImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_index', models.PositiveIntegerField()),
                ('staged_object_key', models.CharField(blank=True, default='', max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('detected_format', models.CharField(blank=True, default='', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('unresolved', 'Unresolved'), ('left', 'Left'), ('right', 'Right'), ('rejected', 'Rejected'), ('invalid', 'Invalid'), ('skipped', 'Skipped non-image')], default='unresolved', max_length=20)),
                ('safe_issue_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uploads.bulkimageimportgroup')),
            ],
            options={
                'ordering': ['group__source_index', 'source_index'],
            },
        ),
        migrations.CreateModel(
            name='BulkImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_laterality', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_image_attachments', to='encounters.screeningencounter')),
                ('image_upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_import_attachment', to='uploads.imageupload')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attachment', to='uploads.bulkimageimportitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_image_attachments', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bulkimageimport',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='bulk_import_unique_org_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='bulkimageimportgroup',
            constraint=models.UniqueConstraint(fields=('bulk_import', 'source_index'), name='bulk_import_unique_group_index'),
        ),
        migrations.AddConstraint(
            model_name='bulkimageimportitem',
            constraint=models.UniqueConstraint(fields=('group', 'source_index'), name='bulk_import_unique_item_index'),
        ),
        migrations.AddConstraint(
            model_name='bulkimageimportitem',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum_sha256', ''), _negated=True), fields=('group', 'checksum_sha256'), name='bulk_import_unique_group_checksum'),
        ),
        migrations.AddConstraint(
            model_name='bulkimageattachment',
            constraint=models.UniqueConstraint(fields=('organization', 'checksum_sha256'), name='bulk_attachment_unique_org_checksum'),
        ),
        migrations.AddConstraint(
            model_name='bulkimageattachment',
            constraint=models.UniqueConstraint(fields=('encounter', 'eye_laterality'), name='bulk_attachment_unique_encounter_eye'),
        ),
    ]
