# Generated by Django 6.0.3 on 2026-08-15 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        ('uploads', '0008_bulkimageimport_bulkimageimportgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bulkimageimport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['processing', 'preview', 'confirmed'])), fields=('organization', 'service_session', 'archive_checksum_sha256'), name='bulk_import_unique_session_archive'),
        ),
    ]
