# Generated by Django 6.0.3 on 2026-08-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        ('patients', '0004_branch_and_safe_sequence'),
        ('uploads', '0009_bulkimageimport_bulk_import_unique_session_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimageimport',
            name='confirmation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkimageimport',
            name='confirmation_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bulkimageimportitem',
            name='permanent_cleanup_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkimageimportitem',
            name='permanent_copy_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='bulkimageimportitem',
            name='permanent_object_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='asset_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_image_assets', to='organizations.organizationbranch'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='asset_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_image_assets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_clinical_image_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='content_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='dataset_eligibility',
            field=models.CharField(choices=[('legacy_policy', 'Legacy consent policy'), ('excluded', 'Excluded'), ('approved', 'Approved')], default='legacy_policy', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='pixel_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='pixel_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='private_object_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='source_format',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='storage_kind',
            field=models.CharField(choices=[('public_media', 'Public media'), ('private_clinical', 'Private clinical')], default='public_media', max_length=24),
        ),
        migrations.AlterField(
            model_name='bulkimageimport',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('preview', 'Ready for review'), ('confirming', 'Confirmation in progress'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='processing', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='imageupload',
            constraint=models.UniqueConstraint(condition=models.Q(('storage_kind', 'private_clinical')), fields=('asset_organization', 'content_sha256'), name='private_image_unique_org_checksum'),
        ),
        migrations.AddConstraint(
            model_name='imageupload',
            constraint=models.CheckConstraint(condition=models.Q(('storage_kind', 'public_media'), models.Q(('private_object_key__gt', ''), ('content_sha256__gt', ''), ('asset_organization__isnull', False), ('asset_branch__isnull', False)), _connector='OR'), name='private_image_requires_metadata'),
        ),
    ]
