# Generated by Django 6.0.3 on 2026-08-28 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_bulkimageimport_confirmation_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmobileimage',
            name='permanent_object_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pendingmobileimage',
            name='staged_object_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='pendingmobileimage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_file', ''), _negated=True), ('staged_object_key__gt', ''), ('permanent_object_key__gt', ''), _connector='OR'), name='pending_mobile_image_has_storage_identity'),
        ),
    ]
