# Generated by Django 6.0.3 on 2026-08-15 19:52

import django.db.models.deletion
import onward_referrals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0013_screeningencounter_service_delivery_snapshot_and_more'),
        ('organizations', '0008_alter_organization_organization_type'),
        ('patients', '0004_branch_and_safe_sequence'),
        ('referrals', '0007_referral_branches'),
        ('reports', '0009_report_attachment_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterResponsibleOptometrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician_name', models.CharField(max_length=255)),
                ('professional_role', models.CharField(default='Optometrist', max_length=120)),
                ('registration_number', models.CharField(max_length=120)),
                ('accepted_at', models.DateTimeField()),
                ('takeover_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_onward_responsibility_actions', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onward_responsibility', to='encounters.screeningencounter')),
                ('optometrist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_onward_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('original_optometrist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_onward_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('previous_optometrist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_onward_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnwardReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_reference', models.CharField(default=onward_referrals.models.onward_reference, editable=False, max_length=40, unique=True)),
                ('clinical_sources', models.JSONField(default=list)),
                ('route', models.CharField(choices=[('originating_hospital', 'Originating hospital'), ('registered_hospital', 'Registered hospital'), ('clinic_download', 'Protected clinic download')], max_length=30)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('superseded', 'Superseded'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='organizations.organizationbranch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_onward_referrals', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='encounters.screeningencounter')),
                ('ocular_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='encounters.oculardiagnosticassessment')),
                ('original_hospital_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='referrals.hospitalreferral')),
                ('originating_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_onward_referrals', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='patients.patient')),
                ('retinal_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onward_referrals', to='reports.structuredreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnwardReferralVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('superseded', 'Superseded'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('urgency', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('expedited', 'Expedited'), ('routine', 'Routine')], max_length=20)),
                ('referral_reason', models.CharField(max_length=255)),
                ('requested_specialist_action', models.TextField()),
                ('relevant_history', models.TextField(blank=True, default='')),
                ('pertinent_findings', models.TextField(blank=True, default='')),
                ('professional_impression', models.TextField(blank=True, default='')),
                ('management_provided', models.TextField(blank=True, default='')),
                ('include_patient_phone', models.BooleanField(default=False)),
                ('recipient_department', models.CharField(blank=True, default='', max_length=160)),
                ('author_snapshot', models.JSONField(default=dict)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('recipient_snapshot', models.JSONField(default=dict)),
                ('clinical_source_snapshot', models.JSONField(default=dict)),
                ('branding_snapshot', models.JSONField(default=dict)),
                ('emergency_escalation_confirmed', models.BooleanField(default=False)),
                ('emergency_escalation_method', models.CharField(blank=True, default='', max_length=80)),
                ('emergency_escalation_note', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_escalation_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.TextField(blank=True, default='')),
                ('void_reason', models.TextField(blank=True, default='')),
                ('pdf_object_key', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_size', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_onward_referral_versions', to=settings.AUTH_USER_MODEL)),
                ('emergency_escalation_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_onward_emergency_escalations', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_onward_referral_versions', to=settings.AUTH_USER_MODEL)),
                ('recipient_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_onward_referral_versions', to='organizations.organization')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='onward_referrals.onwardreferral')),
                ('responsible_optometrist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_onward_referral_versions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_versions', to='onward_referrals.onwardreferralversion')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='OnwardReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('safe_note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referral_events', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='onward_referrals.onwardreferral')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='onward_referrals.onwardreferralversion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnwardReferralAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_onward_referral_availabilities', to=settings.AUTH_USER_MODEL)),
                ('recipient_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referral_availabilities', to='organizations.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_onward_referral_availabilities', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='onward_referrals.onwardreferralversion')),
            ],
        ),
        migrations.CreateModel(
            name='OnwardReferralAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referral_access_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onward_referral_access_events', to='organizations.organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='onward_referrals.onwardreferralversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onwardreferral',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_referrals', to='onward_referrals.onwardreferralversion'),
        ),
        migrations.AddConstraint(
            model_name='onwardreferralversion',
            constraint=models.UniqueConstraint(fields=('referral', 'version_number'), name='unique_onward_referral_version'),
        ),
        migrations.AddConstraint(
            model_name='onwardreferralavailability',
            constraint=models.UniqueConstraint(fields=('version', 'recipient_organization'), name='unique_onward_version_availability'),
        ),
        migrations.AddConstraint(
            model_name='onwardreferralavailability',
            constraint=models.UniqueConstraint(fields=('recipient_organization', 'idempotency_key'), name='unique_onward_availability_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='onwardreferral',
            constraint=models.UniqueConstraint(condition=models.Q(('lifecycle__in', ['draft', 'finalized'])), fields=('encounter',), name='one_active_onward_referral_per_encounter'),
        ),
    ]
